
[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
opacity = 0.9
padding = { x = 0, y = 0 }

[general]
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
