[font]
size = 12

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
